### ISSUE TITLE
Refactor UI to be less resource-heavy

### ISSUE THREAD

**Issue by thomotron** [thomotron/Phinix#39]
### Description
Currently the UI generates content and draws it on every pass. Because this is done each frame, it is constantly running logic in the background which can become very taxing.

### Steps to reproduce
1. Have lots of chat messages
2. Experience awful lag

### Further detail
Generation of content can be run once and deferred for subsequent passes. Perhaps implement an `Update()` method for each UI element and recursively call that after they're created rather than recreate the objects in their entirety.

**Comment by thomotron** [comment]
#26 is a common symptom of this problem

**Comment by exuvo** [comment]
A workaround for #26 is to open phinix settings, disconnect and reconnect. reduces the rendered log to reasonable amounts.

**Comment by exuvo** [comment]
Wonderful work thomotron!
