### ISSUE TITLE
Connecting via `phinix.chat` fails via IPv6

### ISSUE THREAD

**Issue by thomotron** [thomotron/Phinix#54]
### Description
Connecting to `phinix.chat` via the DNS record with an IPv6-enabled connection will fail silently since the server does not listen on an IPv6 endpoint.

### Steps to reproduce
1. Have an IPv6 address
2. Connect to `phinix.chat`
3. Don't actually connect to `phinix.chat` because you can't over IPv6

### Further detail
Switching the bind address to `::0` almost immediately got a connection from a random client out in the wilderness, so it's not like the server is incapable of using v6, it just needs a dual-stack implementation.

**Comment by thomotron** [comment]
That, and if both an `A` and `AAAA` records exist then they should both be attempted

**Comment by thomotron** [comment]
Resolved in e3441aa

**Comment by thomotron** [comment]
It should be trying every record it gets which Microsoft define to be both A and AAAA by default, and when I was testing this with my own v6 connection it seemed to work ok. Does it have any issue connecting via IPv6 with the address itself, or is this purely with name resolution?

I don't have access to a v6 net connection at the moment so I'll give it a look tonight and see if I can replicate it.

**Comment by exuvo** [comment]
I just tried with only the IPv6 address from the game (both via /etc/hosts and raw in the connection window) and that fails. Don't spend a lot of your time on this, i'll just live with having the IPv4 address manually entered in the connection window for now.
