### ISSUE TITLE
Exception on Server Startup

### ISSUE THREAD

**Issue by Balu-bln** [thomotron/Phinix#71]
### Description

If i start the server executable "PhinixServer.exe",
i get a function not found exception:

Unhandled exception: System.MissingMethodException: method not found: "System.String[] System.String.Split(Char, System.StringSplitOptions)".
   in PhinixServer.Server.Main()

### Steps to reproduce
1. start the server

### Further detail
Do i need some extra runtimes to start the server ?

**Comment by Balu-bln** [comment]
Just had a Chat with Tommy from the official discord (https://discord.com/invite/d4Y5xks), he suggested the use of the 0.8.1 Version. (Could be a .NET 6 error)

https://discord.com/channels/363547745564360704/363547749062541314/1036073447538835466
(https://github.com/thomotron/Phinix/releases/tag/v0.8.1)

**Comment by thomotron** [comment]
I'll try building the server on Windows and see if it's any different. I know that the .NET CLI has been giving me trouble when building on Linux lately, so I'm expecting that to be the issue.

**Comment by thomotron** [comment]
I have recompiled the latest build and updated [the release](https://github.com/thomotron/Phinix/releases/tag/v0.8.2). It should be working again now.
